// <auto-generated />
using System;
using KnnResults.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KnnResults.Domain.Migrations
{
    [DbContext(typeof(VADETContext))]
    [Migration("20191213092120_OfferedProductDatetimeChange")]
    partial class OfferedProductDatetimeChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnnResults.Domain.Models.AttributeRejection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttributeSource")
                        .IsRequired();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<int>("OriginalProposalId");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.HasIndex("AttributeSource", "OriginalProposalId")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "Reason", "Time" });

                    b.ToTable("AttributeRejections");
                });

            modelBuilder.Entity("KnnResults.Domain.Models.OfferedAttributeReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("DistanceToAttribute");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ReactionStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ImageId", "AttributeId")
                        .IsUnique();

                    b.ToTable("OfferedAttributeReaction");
                });

            modelBuilder.Entity("KnnResults.Domain.Models.ProductVisualAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId");

                    b.Property<double>("Coverage");

                    b.Property<double>("Distance");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId", "AttributeId")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ProductVisualAttributes");
                });

            modelBuilder.Entity("KnnResults.Domain.Models.VisualAttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttributeSource");

                    b.Property<string>("Candidates")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DiscardedCategories");

                    b.Property<string>("DiscardedProducts");

                    b.Property<double?>("DistanceTreshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("OriginalProposalId");

                    b.Property<string>("Quality")
                        .HasMaxLength(50);

                    b.Property<string>("User");

                    b.Property<string>("WhitelistedCategories");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("AttributeSource", "OriginalProposalId")
                        .IsUnique()
                        .HasFilter("[AttributeSource] IS NOT NULL")
                        .HasAnnotation("SqlServer:Include", new[] { "CreatedAt", "Name" });

                    b.ToTable("VisualAttributeDefinition");
                });

            modelBuilder.Entity("KnnResults.Domain.Models.ZootBataProducts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasMaxLength(50);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Categories")
                        .IsRequired();

                    b.Property<int>("Price");

                    b.Property<string>("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("ZootBataProducts");
                });

            modelBuilder.Entity("KnnResults.Domain.Models.ProductVisualAttributes", b =>
                {
                    b.HasOne("KnnResults.Domain.Models.VisualAttributeDefinition", "Attribute")
                        .WithMany("ProductVisualAttributes")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("FK_ProductVisualAttributes_VisualAttributeDefinition")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KnnResults.Domain.Models.ZootBataProducts", "Product")
                        .WithMany("ProductVisualAttributes")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductVisualAttributes_ZootBataProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
